[project]
name = "lab-04-sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Brandon Chu", email = "bchusch@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.5.6",
    "mysql-connector-python>=26.7.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
    "sqlalchemy>=2.1.1",
]

[project.scripts]
lab-04-sql = "lab_04_sql:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
